# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_applicationsmv_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsmv',
            name='comments',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
