# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationsmv_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsmv',
            name='status',
            field=models.BooleanField(choices=[(True, 'Approve'), (False, 'Rejected')], default=False),
        ),
    ]
