# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20170107_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsmv',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
