# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20170107_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsmv',
            name='status',
            field=models.CharField(max_length=5),
        ),
    ]
