# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dni',
            new_name='role',
        ),
    ]
